### ISSUE TITLE
引入 webpack bar

### ISSUE THREAD

**Issue by RunningCoderLee** [uedlinker/uedlinker-scripts#2]
社区里有个显示 webpack 打包进度的工具，感觉还挺好的，看看是否有必要整合进来

https://github.com/nuxt/webpackbar

另外，打包的时候显示的很多信息比较冗余，可能只是在排查性能的时候会有用，所以能不能做个配置可以自行选择显示与否的

**Comment by LeeWeisheng** [comment]
好的，Nice。会在重构中使用，并可配置。现在将就着用吧。
